sudo: required
language: python
python:
- "2.7"
- "3.5"
- "3.8"
install:
- pip install -U setuptools
- pip install -r requirements.txt
- openssl version -a
script:
- PAYPAL_CLIENT_ID=YOUR_SANDBOX_CLIENT_ID PAYPAL_CLIENT_SECRET=YOUR_SANDBOX_CLIENT_SECRET nosetests --exe
